// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS0KVNyhW5-3y72ojQo0SciuWp-iFPwTk',
    appId: '1:265197532784:web:af8400b9d9849a058726b5',
    messagingSenderId: '265197532784',
    projectId: 'pingpongplayhub1',
    authDomain: 'pingpongplayhub1.firebaseapp.com',
    storageBucket: 'pingpongplayhub1.firebasestorage.app',
    measurementId: 'G-GNXGBESLY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA30kg_rmxjv_b9NVhBskAsrDHi3bVqCIY',
    appId: '1:265197532784:android:9e57a54d40bd194f8726b5',
    messagingSenderId: '265197532784',
    projectId: 'pingpongplayhub1',
    storageBucket: 'pingpongplayhub1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcyKh_7JPPSBpt568mka7sb_S6nj2vlIA',
    appId: '1:265197532784:ios:f512872ff979f6b88726b5',
    messagingSenderId: '265197532784',
    projectId: 'pingpongplayhub1',
    storageBucket: 'pingpongplayhub1.firebasestorage.app',
    iosBundleId: 'com.pingpongplayhub.pingpongPlayhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcyKh_7JPPSBpt568mka7sb_S6nj2vlIA',
    appId: '1:265197532784:ios:f512872ff979f6b88726b5',
    messagingSenderId: '265197532784',
    projectId: 'pingpongplayhub1',
    storageBucket: 'pingpongplayhub1.firebasestorage.app',
    iosBundleId: 'com.pingpongplayhub.pingpongPlayhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS0KVNyhW5-3y72ojQo0SciuWp-iFPwTk',
    appId: '1:265197532784:web:e30c4ea2a7aaf4c88726b5',
    messagingSenderId: '265197532784',
    projectId: 'pingpongplayhub1',
    authDomain: 'pingpongplayhub1.firebaseapp.com',
    storageBucket: 'pingpongplayhub1.firebasestorage.app',
    measurementId: 'G-D2RPHY3K4M',
  );

}