// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtM7RTSF-NGH3MBd45wWPyMuLczK9UNTo',
    appId: '1:801794099668:web:586965130c52ef465aae41',
    messagingSenderId: '801794099668',
    projectId: 'pingpongplayhub',
    authDomain: 'pingpongplayhub.firebaseapp.com',
    storageBucket: 'pingpongplayhub.firebasestorage.app',
    measurementId: 'G-EHCK25FK0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_cgV9ngxcpPcOxpz-kPo1aozvTStRjVU',
    appId: '1:801794099668:android:3cbc86af7c5c2a435aae41',
    messagingSenderId: '801794099668',
    projectId: 'pingpongplayhub',
    storageBucket: 'pingpongplayhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ef1cNtceS9xLwPKobLSC4rO1O14sb7E',
    appId: '1:801794099668:ios:9c14edd21dac27035aae41',
    messagingSenderId: '801794099668',
    projectId: 'pingpongplayhub',
    storageBucket: 'pingpongplayhub.firebasestorage.app',
    iosBundleId: 'com.pingpongplayhub.pingpongPlayhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0ef1cNtceS9xLwPKobLSC4rO1O14sb7E',
    appId: '1:801794099668:ios:9c14edd21dac27035aae41',
    messagingSenderId: '801794099668',
    projectId: 'pingpongplayhub',
    storageBucket: 'pingpongplayhub.firebasestorage.app',
    iosBundleId: 'com.pingpongplayhub.pingpongPlayhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtM7RTSF-NGH3MBd45wWPyMuLczK9UNTo',
    appId: '1:801794099668:web:13b389cd7d69edfd5aae41',
    messagingSenderId: '801794099668',
    projectId: 'pingpongplayhub',
    authDomain: 'pingpongplayhub.firebaseapp.com',
    storageBucket: 'pingpongplayhub.firebasestorage.app',
    measurementId: 'G-5CJ95M8HJ0',
  );

}